@echo off
echo Stopping Java...
taskkill /F /IM java.exe /T >nul 2>&1
echo Deleting backend and data folders...
rd /s /q backend >nul 2>&1
rd /s /q data >nul 2>&1
echo Deleting workflows...
del /q .github\workflows\keep-alive.yml >nul 2>&1
del /q .github\workflows\keep-awake.yml >nul 2>&1
echo Deleting legacy scripts...
del /q move_static.bat del_all.bat push_fix.bat push_to_github.bat update_html.py cleanup_workflows.py copy_images.py fetch_error.py git_push.py migrate_index.py final_move.py merge_static.py >nul 2>&1
echo Done.
